import createClient from "openapi-fetch";
import type { paths } from "./schema"; // Generated by openapi-typescript

const client = createClient<paths>({ baseUrl: "http://localhost:8000" });

export default client;